options(repos = c(CRAN = "https://cloud.r-project.org"))
install.packages("remotes")
remotes::install_version("rlang", version="0.1.1", upgrade = "never", dependencies = F)
remotes::install_version("Rcpp", version="0.12.11", upgrade = "never", dependencies = F)
remotes::install_version("RcppArmadillo", version="0.7.900.2.0", upgrade = "never", dependencies = F)
remotes::install_version("bitops", version="1.0-6", upgrade = "never", dependencies = F)
remotes::install_version("RCurl", version="1.95-4.8", upgrade = "never", dependencies = F)
remotes::install_version("Rtsne", version="0.13", upgrade = "never", dependencies = F)
remotes::install_version("MASS", version="7.3-47", upgrade = "never", dependencies = F)
remotes::install_version("RColorBrewer", version="1.1-2", upgrade = "never", dependencies = F)
remotes::install_version("colorspace", version="1.3-2", upgrade = "never", dependencies = F)
remotes::install_version("munsell", version="0.4.3", upgrade = "never", dependencies = F)
remotes::install_version("gtable", version="0.2.0", upgrade = "never", dependencies = F)
remotes::install_version("digest", version="0.6.12", upgrade = "never", dependencies = F)
remotes::install_version("memoise", version="1.1.0", upgrade = "never", dependencies = F)
remotes::install_version("htmltools", version="0.3.6", upgrade = "never", dependencies = F)
remotes::install_version("pkgconfig", version="2.0.1", upgrade = "never", dependencies = F)
remotes::install_version("magrittr", version="1.5", upgrade = "never", dependencies = F)
remotes::install_version("lazyeval", version="0.2.0", upgrade = "never", dependencies = F)
remotes::install_version("tibble", version="1.3.3", upgrade = "never", dependencies = F)
remotes::install_version("stringi", version="1.1.5", upgrade = "never", dependencies = F)
remotes::install_version("stringr", version="1.2.0", upgrade = "never", dependencies = F)
remotes::install_version("glue", version="1.1.1", upgrade = "never", dependencies = F)
remotes::install_version("plyr", version="1.8.4", upgrade = "never", dependencies = F)
remotes::install_version("reshape2", version="1.4.2", upgrade = "never", dependencies = F)
remotes::install_version("assertthat", version="0.2.0", upgrade = "never", dependencies = F)
remotes::install_version("bindr", version="0.1", upgrade = "never", dependencies = F)
remotes::install_version("R6", version="2.2.2", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/plogr/plogr_0.1-1.tar.gz", repos = NULL) # What version should it be? bindrcpp 0.2 requires plogr
remotes::install_version("bindrcpp", version="0.2", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/BH/BH_1.62.0-1.tar.gz", repos = NULL) # What version should it be?
install.packages("https://cran.r-project.org/src/contrib/Archive/dichromat/dichromat_2.0-0.tar.gz", repos = NULL) # What version should it be? scales 0.4.1 requires dichromat
install.packages("https://cran.r-project.org/src/contrib/Archive/labeling/labeling_0.3.tar.gz", repos = NULL) # What version should it be? scales 0.4.1 requires labeling
remotes::install_version("scales", version="0.4.1", upgrade = "never", dependencies = F)
remotes::install_version("pheatmap", version="1.0.8", upgrade = "never", dependencies = F)
remotes::install_version("ggplot2", version="2.2.1", upgrade = "never", dependencies = F)
remotes::install_version("gridExtra", version="2.2.1", upgrade = "never", dependencies = F)
remotes::install_version("viridisLite", version="0.2.0", upgrade = "never", dependencies = F)
remotes::install_version("viridis", version="0.4.0", upgrade = "never", dependencies = F)
remotes::install_version("RJSONIO", version="1.3-1.2", upgrade = "never", dependencies = F)
remotes::install_version("jsonlite", version="1.6", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/yaml/yaml_2.1.14.tar.gz", repos = NULL) # What version should it be? htmlwidgets 0.8 requires yaml
remotes::install_version("htmlwidgets", version="0.8", upgrade = "never", dependencies = F)
remotes::install_version("png", version="0.1-7", upgrade = "never", dependencies = F)
remotes::install_version("base64enc", version="0.1-3", upgrade = "never", dependencies = F)
remotes::install_version("modeltools", version="0.2-21", upgrade = "never", dependencies = F)
remotes::install_version("flexmix", version="2.3-13", upgrade = "never", dependencies = F)
remotes::install_version("mvtnorm", version="1.0-6", upgrade = "never", dependencies = F)
remotes::install_version("DEoptimR", version="1.0-8", upgrade = "never", dependencies = F)
remotes::install_version("robustbase", version="0.92-7", upgrade = "never", dependencies = F)
remotes::install_version("mgcv", version="1.8-23", upgrade = "never", dependencies = F)
remotes::install_version("nlme", version="3.1-131.1", upgrade = "never", dependencies = F)
remotes::install_version("iterators", version="1.0.8", upgrade = "never", dependencies = F)
remotes::install_version("foreach", version="1.4.3", upgrade = "never", dependencies = F)
remotes::install_version("lattice", version="0.20-35", upgrade = "never", dependencies = F)
remotes::install_version("matrixStats", version="0.52.2", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/irlba/irlba_2.1.1.tar.gz", repos = NULL) # What version should it be? igraph 1.1.1 requires irlba version 2.1.1 or higher
remotes::install_version("igraph", version="1.1.1", upgrade = "never", dependencies = F)
remotes::install_version("networkD3", version="0.4", upgrade = "never", dependencies = F)
remotes::install_version("cluster", version="2.0.6", upgrade = "never", dependencies = F)
remotes::install_version("data.table", version="1.10.4", upgrade = "never", dependencies = F)
remotes::install_version("backports", version="1.1.0", upgrade = "never", dependencies = F)
remotes::install_version("Formula", version="1.2-1", upgrade = "never", dependencies = F)
remotes::install_version("latticeExtra", version="0.6-28", upgrade = "never", dependencies = F)
remotes::install_version("acepack", version="1.4.1", upgrade = "never", dependencies = F)
remotes::install_version("checkmate", version="1.8.3", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/evaluate/evaluate_0.10.tar.gz", repos = NULL) # What version should it be? knitr 1.16 requires evaluate version 0.10 or higher
install.packages("https://cran.r-project.org/src/contrib/Archive/highr/highr_0.6.tar.gz", repos = NULL) # What version should it be? knitr 1.16 requires highr version 0.6 or higher
remotes::install_version("mime", version="0.5", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/markdown/markdown_0.7.7.tar.gz", repos = NULL) # What version should it be? knitr 1.16 requires markdown
remotes::install_version("knitr", version="1.16", upgrade = "never", dependencies = F)
remotes::install_version("htmlTable", version="1.9", upgrade = "never", dependencies = F)
remotes::install_version("Hmisc", version="4.0-3", upgrade = "never", dependencies = F)
remotes::install_version("httpuv", version="1.3.5", upgrade = "never", dependencies = F)
remotes::install_version("xtable", version="1.8-2", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/sourcetools/sourcetools_0.1.5.tar.gz", repos = NULL) # What version should it be? shiny 1.0.3 requires sourcetools
remotes::install_version("shiny", version="1.0.3", upgrade = "never", dependencies = F)
remotes::install_version("shinydashboard", version="0.6.1", upgrade = "never", dependencies = F)
remotes::install_version("gtools", version="3.5.0", upgrade = "never", dependencies = F)
remotes::install_version("gdata", version="2.18.0", upgrade = "never", dependencies = F)
remotes::install_version("RMTstat", version="0.3", upgrade = "never", dependencies = F)
remotes::install_version("doParallel", version="1.0.10", upgrade = "never", dependencies = F)
remotes::install_version("caTools", version="1.17.1", upgrade = "never", dependencies = F)
remotes::install_version("gplots", version="3.0.1", upgrade = "never", dependencies = F)
remotes::install_version("ROCR", version="1.0-7", upgrade = "never", dependencies = F)
remotes::install_version("blob", version="1.1.0", upgrade = "never", dependencies = F)
remotes::install_version("WriteXLS", version="4.0.0", upgrade = "never", dependencies = F)
remotes::install_version("brew", version="1.0-6", upgrade = "never", dependencies = F)
remotes::install_version("survival", version="2.41-3", upgrade = "never", dependencies = F)
remotes::install_version("registry", version="0.3", upgrade = "never", dependencies = F)
remotes::install_version("MatrixModels", version="0.4-1", upgrade = "never", dependencies = F)
remotes::install_version("Rook", version="1.1-1", upgrade = "never", dependencies = F)
remotes::install_version("SparseM", version="1.77", upgrade = "never", dependencies = F)
remotes::install_version("DBI", version="0.7", upgrade = "never", dependencies = F)
remotes::install_version("pkgmaker", version="0.22", upgrade = "never", dependencies = F)
remotes::install_version("rngtools", version="1.2.4", upgrade = "never", dependencies = F)
remotes::install_version("foreign", version="0.8-69", upgrade = "never", dependencies = F)
remotes::install_version("bit", version="1.1-12", upgrade = "never", dependencies = F)
remotes::install_version("ff", version="2.2-13", upgrade = "never", dependencies = F)
remotes::install_version("distillery", version="1.0-4", upgrade = "never", dependencies = F)
remotes::install_version("XML", version="3.98-1.9", upgrade = "never", dependencies = F)
remotes::install_version("nnet", version="7.3-12", upgrade = "never", dependencies = F)
remotes::install_version("locfit", version="1.5-9.1", upgrade = "never", dependencies = F)
remotes::install_version("bit64", version="0.9-7", upgrade = "never", dependencies = F)
remotes::install_version("RSQLite", version="2.0", upgrade = "never", dependencies = F)
remotes::install_version("doRNG", version="1.6.6", upgrade = "never", dependencies = F)
remotes::install_version("quantreg", version="5.33", upgrade = "never", dependencies = F)
remotes::install_version("beeswarm", version="0.2.3", upgrade = "never", dependencies = F)
remotes::install_version("e1071", version="1.6-8", upgrade = "never", dependencies = F)
remotes::install_version("statmod", version="1.4.30", upgrade = "never", dependencies = F)
remotes::install_version("pcaPP", version="1.9-72", upgrade = "never", dependencies = F)
remotes::install_version("Matrix", version="1.2-10", upgrade = "never", dependencies = F)
remotes::install_version("nloptr", version="1.0.4", upgrade = "never", dependencies = F)
remotes::install_version("minqa", version="1.2.4", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/RcppEigen/RcppEigen_0.3.2.9.0.tar.gz", repos = NULL) # What version should it be? lme4 1.1-13 requires RcppEigen >= 0.3.2.0.0
remotes::install_version("lme4", version="1.1-13", upgrade = "never", dependencies = F)
remotes::install_version("pbkrtest", version="0.4-7", upgrade = "never", dependencies = F)
remotes::install_version("car", version="2.1-5", upgrade = "never", dependencies = F)
remotes::install_version("Lmoments", version="1.2-3", upgrade = "never", dependencies = F)
remotes::install_version("extRemes", version="2.0-8", upgrade = "never", dependencies = F)
remotes::install_version("rrcov", version="1.4-3", upgrade = "never", dependencies = F)
remotes::install_version("KernSmooth", version="2.23-15", upgrade = "never", dependencies = F)
remotes::install_version("vipor", version="0.4.5", upgrade = "never", dependencies = F)
remotes::install_version("codetools", version="0.2-15", upgrade = "never", dependencies = F)
remotes::install_version("rjson", version="0.2.15", upgrade = "never", dependencies = F)
remotes::install_version("rpart", version="4.1-11", upgrade = "never", dependencies = F)
remotes::install_version("class", version="7.3-14", upgrade = "never", dependencies = F)
remotes::install_version("Cairo", version="1.5-9", upgrade = "never", dependencies = F)
remotes::install_version("ggbeeswarm", version="0.5.3", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/mclust/mclust_5.2.tar.gz", repos = NULL) # What version should it be? fpc 2.1-10 requires it
install.packages("https://cran.r-project.org/src/contrib/Archive/prabclus/prabclus_2.2-6.tar.gz", repos = NULL) # What version should it be? fpc 2.1-10 requires it
install.packages("https://cran.r-project.org/src/contrib/Archive/diptest/diptest_0.75-7.tar.gz", repos = NULL) # What version should it be? fpc 2.1-10 requires it
install.packages("https://cran.r-project.org/src/contrib/Archive/kernlab/kernlab_0.9-25.tar.gz", repos = NULL) # What version should it be? fpc 2.1-10 requires it
install.packages("https://cran.r-project.org/src/contrib/Archive/trimcluster/trimcluster_0.1-2.tar.gz", repos = NULL) # What version should it be? fpc 2.1-10 requires it
install.packages("https://cran.r-project.org/src/contrib/Archive/fpc/fpc_2.1-10.tar.gz", repos = NULL) # What version should it be? dendextend 1.3.0 requires fpc
install.packages("https://cran.r-project.org/src/contrib/Archive/whisker/whisker_0.3-2.tar.gz", repos = NULL) # What version should it be? dendextend 1.3.0 requires whisker
install.packages("https://cran.r-project.org/src/contrib/Archive/dendextend/dendextend_1.3.0.tar.gz", repos = NULL) # What version should it be? d3heatmap 0.6.1.1 requires dendextend
remotes::install_version("d3heatmap", version="0.6.1.1", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/curl/curl_2.3.tar.gz", repos = NULL) # What version should it be? httr 1.2.1 requires curl
install.packages("https://cran.r-project.org/src/contrib/Archive/openssl/openssl_0.9.6.tar.gz", repos = NULL) # What version should it be? httr 1.2.1 requires openssl
remotes::install_version("httr", version="1.2.1", upgrade = "never", dependencies = F)
remotes::install_version("dplyr", version="0.7.1", upgrade = "never", dependencies = F)

# FAILS
remotes::install_version("rPython", version="0.0-6", upgrade = "never", dependencies = F)
install.packages("https://cran.r-project.org/src/contrib/Archive/rPython/rPython_0.0-6.tar.gz", repos = NULL)


install.packages("https://www.bioconductor.org/src/contrib/edgeR_3.18.1.tar.gz", repos = NULL)

# NOT FOUND PACKAGES
remotes::install_version("SCAN.UPC", version="2.18.0", upgrade = "never", dependencies = F) # FAILS (not found)
remotes::install_version("sva", version="3.26.0", upgrade = "never", dependencies = F) # FAILS (not found)
remotes::install_version("genefilter", version="1.58.1", upgrade = "never", dependencies = F) #  FAILS (not found)
remotes::install_version("affyio", version="1.46.0", upgrade = "never", dependencies = F) #  FAILS (not found)
remotes::install_version("affy", version="1.54.0", upgrade = "never", dependencies = F) #  FAILS (not found)
remotes::install_version("GEOquery", version="2.42.0", upgrade = "never", dependencies = F) #  FAILS (not found)
remotes::install_version("oligo", version="1.40.1", upgrade = "never", dependencies = F)
remotes::install_version("Biostrings", version="2.44.1", upgrade = "never", dependencies = F)
remotes::install_version("XVector", version="0.16.0", upgrade = "never", dependencies = F)
remotes::install_version("oligoClasses", version="1.38.0", upgrade = "never", dependencies = F)
remotes::install_version("scde", version="2.5.0", upgrade = "never", dependencies = F)
remotes::install_version("edgeR", version="3.18.1", upgrade = "never", dependencies = F)
remotes::install_version("BiocParallel", version="1.10.1", upgrade = "never", dependencies = F)
remotes::install_version("DESeq2", version="1.16.1", upgrade = "never", dependencies = F)
remotes::install_version("SummarizedExperiment", version="1.8.1", upgrade = "never", dependencies = F)
remotes::install_version("DelayedArray", version="0.4.1", upgrade = "never", dependencies = F)
remotes::install_version("GenomicRanges", version="1.30.3", upgrade = "never", dependencies = F)
remotes::install_version("GenomeInfoDb", version="1.14.0", upgrade = "never", dependencies = F)
remotes::install_version("IRanges", version="2.12.0", upgrade = "never", dependencies = F)
remotes::install_version("S4Vectors", version="0.16.0", upgrade = "never", dependencies = F)
remotes::install_version("SC3", version="1.4.2", upgrade = "never", dependencies = F)
remotes::install_version("scater", version="1.4.0", upgrade = "never", dependencies = F)
remotes::install_version("Biobase", version="2.36.2", upgrade = "never", dependencies = F)
remotes::install_version("BiocGenerics", version="0.24.0", upgrade = "never", dependencies = F)
remotes::install_version("limma", version="3.32.2", upgrade = "never", dependencies = F)
remotes::install_version("BiocInstaller", version="1.28.0", upgrade = "never", dependencies = F)
remotes::install_version("scLVM", version="0.99.3", upgrade = "never", dependencies = F)
remotes::install_version("annotate", version="1.54.0", upgrade = "never", dependencies = F)
remotes::install_version("tximport", version="1.4.0", upgrade = "never", dependencies = F)
remotes::install_version("zlibbioc", version="1.22.0", upgrade = "never", dependencies = F)
remotes::install_version("preprocessCore", version="1.38.1", upgrade = "never", dependencies = F)
remotes::install_version("AnnotationDbi", version="1.38.1", upgrade = "never", dependencies = F)
remotes::install_version("biomaRt", version="2.32.1", upgrade = "never", dependencies = F)
remotes::install_version("geneplotter", version="1.54.0", upgrade = "never", dependencies = F)
remotes::install_version("pcaMethods", version="1.68.0", upgrade = "never", dependencies = F)
remotes::install_version("affxparser", version="1.48.0", upgrade = "never", dependencies = F)
remotes::install_version("rhdf5", version="2.20.0", upgrade = "never", dependencies = F)
remotes::install_version("GenomeInfoDbData", version="0.99.0", upgrade = "never", dependencies = F)








