rails filter_de_results[03kum6] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[11zt7k] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[1isi3i] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[2dttxa] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[5s6ddy] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[7waxvc] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[7whf6y] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[9eh3ub] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[9flczz] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[9t0kr0] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[b7dks5] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[ec2p41] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[giwkcv] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[j5r7zf] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[lutged] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[mx095d] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[o57824] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[oyrad5] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[r7v6gd] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[wcunlb] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[wdelms] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[wkn19g] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[x36tv7] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[ymbw0c] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[zirgp6] --trace 2>&1 > log/filter_de_results.log
rails filter_de_results[zjffs0] --trace 2>&1 > log/filter_de_results.log
