source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


ruby '2.6.6'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'                                                                                                                                                      
#gem 'rails', '~> 5.2.4', '>= 5.2.4.4'
gem "rails", '~> 5.0.0', '>= 5.0.0.1'
# Use postgresql as the database for Active Record                                                                                                                                                                   
gem 'pg', '~> 1.5'
# Use Puma as the app server                                                                                                                                                                                         
#gem 'puma', '~> 3.11'
gem 'unicorn'
# Use SCSS for stylesheets                                                                                                                                                                                           
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets                                                                                                                                                                   
gem 'uglifier', '>= 1.3.0'
# See https://github.com/rails/execjs#readme for more supported runtimes                                                                                                                                             
# gem 'mini_racer', platforms: :ruby                                                                                                                                                                                 

# Use CoffeeScript for .coffee assets and views                                                                                                                                                                      
gem 'coffee-rails', '~> 4.2'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks                                                                                                       
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder                                                                                                                                            
gem 'jbuilder', '~> 2.5'

gem 'devise'
gem 'jquery-ui-rails'
gem 'daemons'
gem 'delayed_job_active_record'
gem 'jquery-datatables-rails'
gem 'descriptive_statistics'
gem 'sys-proctable'
gem 'rails4-autocomplete'
gem 'jquery-fileupload-rails'
#gem 'paperclip', "~>4.3.2"
gem 'multipart-parser'
gem 'haml'
gem 'activerecord-session_store'
gem "font-awesome-rails"
#gem 'mimemagic', "0.3.0"
gem 'paperclip'
gem 'mimemagic'
gem 'jquery-rails'


# Use jquery as the JavaScript library                                                                                                                                                         
#gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks                                                                                 
#gem 'turbolinks', '~> 5'                                                                                                                                                                      
#gem 'jquery-turbolinks'                                                                                                                                                                       
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder                                                                                                                      
#gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production                                                                                                                                          
# gem 'redis', '~> 3.0'                                                                                                                                                                        
# Use ActiveModel has_secure_password                                                                                                                                                          
# gem 'bcrypt', '~> 3.1.7'                                                                                                                                                                     

# Use Capistrano for deployment                                                                                                                                                                
# gem 'capistrano-rails', group: :development                                                                                                                                                  

# Reduces boot times through caching; required in config/boot.rb                                                                                                                                                  
gem 'bootsnap', '>= 1.1.0', require: false


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console                                                                                                                               
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.                                                                                                                
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '>= 3.0.5', '< 3.2'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring                                                                                
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver                                                                                                                                                  
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome                                                                                                                                     
  gem 'chromedriver-helper'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem                                                                                                                                          
#gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

#group :development, :test do
#  # Call 'byebug' anywhere in the code to stop execution and get a debugger console                                                                                                            
#  gem 'byebug', platform: :mri
#end

#group :development do
#  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.                                                                                                  
#  gem 'web-console', '>= 3.3.0'
#  gem 'listen', '~> 3.0.5'
#  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring                                                             
#  gem 'spring'
#  gem 'spring-watcher-listen', '~> 2.0.0'
#end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem                                                                                                                       
gem 'tzinfo-data' #, platforms: [:mingw, :mswin, :x64_mingw, :jruby]
